spring:
  datasource:
    url: jdbc:oracle:thin:@db.cotos.ricoh.co.jp:1521/pdb1
    username: cotos_product
    password: cotosissharedprocess
    driverClassName: oracle.jdbc.OracleDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        default_schema: cotos_product
logging:
  level:
    org:
      hibernate:
        SQL: off
        orm:
          jdbc:
            bind: off
