spring:
  datasource:
    url: jdbc:oracle:thin:@st-db-aws.cotos.ricoh.co.jp:1521/pdb1
    username: cotos_st_6
    password: cotosst6issharedprocess
    driverClassName: oracle.jdbc.OracleDriver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        default_schema: cotos_st_6
  mail:
    host: st.shipyard.cotos.ricoh.co.jp
    port: 1025
cotos:
  authentication: https://st-api-6-aws.cotos.ricoh.co.jp/auth/api/auth
  disp:
    urls:
      domain: https://st-6-aws.cotos.ricoh.co.jp/
      screenName: ContractScreen
