spring:
  datasource:
    url: jdbc:oracle:thin:@prdst-db-aws.cotos.ricoh.co.jp:1521/pdb1
    username: cotos_st
    password: cotosstissharedprocess
    driverClassName: oracle.jdbc.OracleDriver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        default_schema: cotos_st
cotos:
  authentication: https://st-api-aws.cotos.ricoh.co.jp/auth/api/auth
