spring:
  datasource:
    url: jdbc:oracle:thin:@db-aws.cotos.ricoh.co.jp:1521/pdb1
    username: cotos_product
    password: cotosissharedprocess
    driverClassName: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        default_schema: cotos_product
cotos:
  authentication: https://api-aws.cotos.ricoh.co.jp/auth/api/auth
logging:
  level:
    org:
      hibernate:
        SQL: off
        type:
          descriptor:
            sql:
              BasicBinder: off
